# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: posse_cup_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: posse_cup_test
  pool: 5
  timeout: 5000
  host: localhost
