# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 024fbec95085827e10915eb5847185a555e3f70bd6846f1bdfb47c5d34c10805564ea16a1185e98ad0d1192099c6fa24ec24157e41411ad66ece7214de64e3d9

test:
  secret_key_base: df1ba1e4277f381dd3b83efac53c70f1fceca39493f8570834be5f18304521c7da0af5d7ba6caa486377696f4911688d4c1e3c3e06e1c19cbc68363c49b9e9c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
